name: Discord Terror Zone Bot

on:
  schedule:
    - cron: '1 * * * *'  # Runs 1 minute after every hour

jobs:
  run-discord-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run Bot
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      run: |
        python main.py 2>&1 | tee output.log
